name: Basic CI

on: [push]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run python script
        run: |
          pip install -r requirements.txt
          cd WB_CICD_for_Machine_Learning 
          python ci.py
